#!/usr/bin/env python

import sys
import re
import subprocess
old, new, branch = sys.stdin.read().split()
proc = subprocess.Popen(["git", "rev-list", "--oneline","--first-parent" , "%s..%s" %(old, new)], stdout=subprocess.PIPE)
commitMessage=str(proc.stdout.readlines()[0]) 
pattern1 = "[A-Z]{2,}-[0-9]\:"
pattern2 = "Merge pull request #[0-9]"
print(commitMessage)
if bool(re.search(pattern1, commitMessage)) == False and bool(re.search(pattern2, commitMessage)) == False:
    print("Bad Commit")
    exit(1)
